# Aplicación de visualización de datos del Programa de Monitoreo de Cuerpos de Agua de Occidente (CAO)

library(shiny)
library(shinythemes)
library(shinydashboard)
library(tidyverse)
library(openxlsx)
library(qdap)
library(lubridate)
library(vtable)
library(DT)
library(shinyWidgets)
library(ggtext)
library(vegan)

source('módulos/utils.R')
source('módulos/server.R')
source('módulos/ui.R')

shinyApp(ui, server) 